<a href="https://colab.research.google.com/github/DarkLyng/Proyecto_Modelos/blob/main/Proyecto_Modelos_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Preparar datos**

In [ ]:
#Bibliotecas de Python

import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import csv

warnings.filterwarnings('ignore')

In [ ]:
xls = pd.ExcelFile("/content/Contoso Sales.xlsx")
print(xls.sheet_names)

['DimChannel', 'DimGeography', 'DimProduct', 'DimProductCategory', 'DimProductSubCategory', 'DimPromotion', 'DimStores']

In [ ]:
dimchannel = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimChannel")
dimgeography = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimGeography")
dimproduct = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimProduct")
dimproductcat = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimProductCategory")
dimproductsubcat = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimProductSubCategory")
dimpromotion = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimPromotion")
dimstores = pd.read_excel("/content/Contoso Sales.xlsx", sheet_name="DimStores")

In [ ]:
dimchannel.info

<bound method DataFrame.info of    ChannelKey ChannelName
0           1       Store
1           2      Online
2           3     Catalog
3           4    Reseller>

In [ ]:
dimgeography.info

<bound method DataFrame.info of      GeographyKey  ContinentName RegionCountryName
0             302  North America     United States
1             366  North America     United States
2             369  North America     United States
3             370  North America     United States
4             371  North America     United States
..            ...            ...               ...
669           762         Europe            France
670           766         Europe            France
671           767         Europe            France
672           775         Europe            France
673           777         Europe            France

[674 rows x 3 columns]>

In [ ]:
dimproduct.info

<bound method DataFrame.info of       ProductKey                                        ProductName  \
0            873              Contoso Wireless Laser Mouse E50 Grey
1            874  Contoso Wireless Notebook Optical Mouse X205 B...
2            875  Contoso Wireless Notebook Optical Mouse X205 W...
3            876  Contoso Wireless Notebook Optical Mouse X205 Blue
4            877  Contoso Wireless Notebook Optical Mouse X205 S...
...          ...                                                ...
1685        2498           Contoso Phone Tough Skin Case E140 Black
1686        2502                Contoso Touch Stylus Pen E150 Black
1687        2509  Contoso Original K1m Li-Ion Standard Battery E...
1688        2512      Contoso Bluetooth Active Headphones L15 Black
1689        2516                 Contoso In-Line Coupler E180 Black

                                     ProductDescription  \
0     Advanced 2.4 GHz cordless technology makes fre...
1     Wireless notebook mouse, long battery life, co...
2     Wireless notebook mouse, long battery life, co...
3     Wireless notebook mouse, long battery life, co...
4     Wireless notebook mouse, long battery life, co...
...                                                 ...
1685    Bottom flaps up for docking, rugged rubber case
1686  The sensitive slanted stylus tip gives you smo...
1687  Stay in touch longer by getting battery power ...
1688  Play time up to 6 hours, talk time up to 7 hou...
1689  Designed for new modular, different location w...

      ProductSubcategoryKey  Manufacturer BrandName  ClassID ClassName  \
0                        22  Contoso, Ltd   Contoso        1   Economy
1                        22  Contoso, Ltd   Contoso        3    Deluxe
2                        22  Contoso, Ltd   Contoso        3    Deluxe
3                        22  Contoso, Ltd   Contoso        3    Deluxe
4                        22  Contoso, Ltd   Contoso        3    Deluxe
...                     ...           ...       ...      ...       ...
1685                     33  Contoso, Ltd   Contoso        1   Economy
1686                     33  Contoso, Ltd   Contoso        1   Economy
1687                     33  Contoso, Ltd   Contoso        1   Economy
1688                     33  Contoso, Ltd   Contoso        3    Deluxe
1689                     33  Contoso, Ltd   Contoso        1   Economy

      ColorID ColorName             Size  Weight  UnitCost  UnitPrice
0          11      Grey              NaN     NaN     10.69      20.96
1           2     Black              NaN     NaN     43.06     129.95
2           8     White              NaN     NaN     43.06     129.95
3           3      Blue              NaN     NaN     43.06     129.95
4           7    Silver              NaN     NaN     43.06     129.95
...       ...       ...              ...     ...       ...        ...
1685        2     Black  2.5 x 0.5 x 4.8     5.0     12.09      23.72
1686        2     Black  4.1 x 0.2 x 0.2     0.3      5.09       9.99
1687        2     Black  2.5 x 1.5 x 4.8     0.6      2.07       4.06
1688        2     Black      6 x 6 x 0.5    12.8     43.07     129.99
1689        2     Black  3.5 x 0.8 x 4.5     1.0      1.71       3.35

[1690 rows x 14 columns]>

In [ ]:
dimproductcat.head()

   ProductCategoryKey         ProductCategory
0                   1                   Audio
1                   2            TV and Video
2                   3               Computers
3                   4  Cameras and camcorders
4                   5             Cell phones

In [ ]:
dimproductsubcat.head()

   ProductSubcategoryKey ProductSubcategoryName  ProductCategoryKey
0                      1                MP4&MP3                   1
1                      2               Recorder                   1
2                      3                  Radio                   1
3                      4          Recording Pen                   1
4                      5             Headphones                   1

In [ ]:
dimpromotion.head()

,PromotionKey,PromotionLabel,PromotionName,DiscountPercent,StartDate,EndDate,Promo_days
0,1,1,No Discount,0.00,2003-01-01,2010-12-31,2921
1,2,2,North America Spring Promotion,0.05,2007-01-01,2007-03-31,89
2,3,3,North America Back-to-School Promotion,0.10,2007-07-01,2007-09-30,91
3,4,4,North America Holiday Promotion,0.20,2007-11-01,2007-12-31,60
4,5,5,Asian Holiday Promotion,0.15,2007-11-01,2008-01-31,91

In [ ]:
dimstores.head()

,StoreKey,GeographyKey,StoreType,StoreName,EmployeeCount,SellingAreaSize
0,1,693,Store,Contoso Seattle No.1 Store,17.0,462
1,2,693,Store,Contoso Seattle No.2 Store,25.0,700
2,3,856,Store,Contoso Kennewick Store,26.0,680
3,4,424,Store,Contoso Bellevue Store,19.0,455
4,5,677,Store,Contoso Redmond Store,33.0,560